spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
        git:
          uri: https://github.com/HusyCoding/springcloud-chapters
          search-paths: eureka-server-config/shareconfig
          username:
          password:
          default-label: master

  application:
    name: eureka-server-config
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka