spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/share
        git:
          uri: https://github.com/HusyCoding/springcloud-chapters.git
          search-paths: shareconfig
#          username:
#          password:
      label: master
  profiles:
    active: native
  application:
    name: eureka-server-config
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka