server:
  port: 8025
spring:
  application:
    name: eureka-client-monitor
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-client-hystrix-feign,eureka-client-hystrix-ribbon
  cluster-name-expression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/