---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8002/eureka/,http://127.0.0.1:8003/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8003/eureka/
---
spring:
  profiles: peer3
  application:
    name: eureka-server
server:
  port: 8003
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/