---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2/eureka/,http://peer3/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/
---
spring:
  profiles: peer3
  application:
    name: eureka-server
server:
  port: 8003
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/