---
server:
  port: 8101
spring:
  profiles: client1
  application:
    name: eureka-client-producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
---
server:
  port: 8102
spring:
  profiles: client2
  application:
    name: eureka-client-producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
