spring:
  application:
    name: eureka-client-hystrix-feign
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8203
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
feign:
  hystrix:
    enabled: true
